### ISSUE TITLE
css: colgroup col etc help

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/TorZillaPrint#16]
```css
  .anchor-up {
    width: 0; 
    height: 0; 
    border-left: 5px solid transparent;
    border-right: 5px solid transparent;
    border-bottom: 10px solid black;
    margin-left: 10px;
  }
  .anchor-down{
    width: 0; 
    height: 0; 
    border-left: 5px solid transparent;
    border-right: 5px solid transparent;
    border-top: 10px solid black;
    margin-right: 10px;
  }
```

```html
  <!-- TESTING ANCHORS --->
  <table id="tb8">
    <col width="2%"><col width="48%"><col width="48%"><col width="2%">
    <thead>
      <tr>
        <th><a href="#blah"><div class="anchor-up"></div></a></th>
        <th colspan="2">add achors test</th>
        <th><a href="#blahblah"><div class="anchor-down"></div></a></th>
      </tr>
    </thead>
    <colgroup><col span="2" width="50%"><col span="2" width="50%">
      <tr><td>test</td><td>trying to use colgroup and col properties</td></tr>
      <tr><td colspan="2">using repetitve colspan="2"</td>
          <td colspan="2">which sucks</td>
          <!-- adding colspan=2 twice (or more) for each row sucks -->
      </tr>
    </colgroup>
  </table>
```

here's a pic
![anchors](https://user-images.githubusercontent.com/16656956/50667340-a5183a80-0fb0-11e9-90ae-045814b3370a.png)

two issues
- make anchor-up cell left aligned (it is by default) and anchor-down cell right aligned (at 2% it *looks* good but anchor-down on the right is actually left-aligned)
- after the thead row, I don't want to have to get all spammy with `colspan=x` for each td (and some table contents might get more columns)
   * tried using my uber limited css knowledge and colgroup, col .. but I fail miserably because I am not a css junkie

It's something really simple, for sure, but I suck, hence this issue :)
