### ISSUE TITLE
css weird issue: class "intro" doesn't scale

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/TorZillaPrint#32]
on desktop all is fine, but on my Android: this is what I see (cropped)

![droid](https://user-images.githubusercontent.com/16656956/56088840-33397200-5e78-11e9-901d-e2327e5feeca.jpg)

My Droid is 360x640, but reports inner window as 980x1522 (I'm not an expert here, so excuse me if I use the wrong terminology). That's not the issue (I think, this is just droid using dpi or whatever to fit the contents/table etc as 900px wide etc), the problem is, as you can see, that font-size 12px is not respected (inherited from body). This is for all `intro` classes. The pic shows the first one.

```css
/* used for descriptions after th */
table td.intro {
  text-align: left;
  line-height: 1.5em;
  padding-bottom: 10px;
}
```

```js
    <tr><td colspan="2" class="intro">
      <span class="no_color">blah blah blah</span>
    </td></tr>
```

Have I done something wrong here. I am at a loss as to how to fix this. Need a CSS expert @overdodactyl
